action: ??? # train or test
name: ??? # name of the experiment needed for the logs
modality: ["RGB", "EMG"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models

train:
  num_iter: 350 #5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 1 # clips adopted in training
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
    EMG: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16
    EMG: 0

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
    EMG: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 16
    EMG: 0

dataset:
  annotations_path: train_val # path for the annotations data
  shift: ??? # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  RGB:
    data_path: ??? # path to RGB data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: I3D_AN_dense_25
  EMG:
    data_path: ??? # path to RGB data
    features_name: I3D_AN_dense_25
  Event: # not needed for the project
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: TRNClassifier
    normalize: False
    kwargs: {}
    lr_steps: 3000
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7
  EMG:
    model: EMG_CNN #EMGClassifier
    dropout: 0.5
    normalize: False
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9

#Da aggiungere EMG
